#!/usr/bin/env bash
# Copy the repo-root install.sh into the worker bundle, if it exists.
# Run from anywhere before `npx wrangler deploy`.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
src="$here/../install.sh"
mkdir -p "$here/public-install"
if [ -f "$src" ]; then
  cp "$src" "$here/public-install/install.sh"
  node -e 'const fs=require("fs");const t=fs.readFileSync(process.argv[1],"utf8");fs.writeFileSync(process.argv[2],"// Generated by sync-install.sh. Do not edit.\nexport default "+JSON.stringify(t)+";\n")' \
    "$here/public-install/install.sh" "$here/src/installer.js"
  echo "synced install.sh ($(wc -c < "$src") bytes)"
else
  rm -f "$here/public-install/install.sh"
  printf '%s\n' '// Placeholder. deploy-site/sync-install.sh overwrites this file with the real' \
    '// installer text when ../install.sh exists. null means "not published yet".' \
    'export default null;' > "$here/src/installer.js"
  echo "no ../install.sh found; /install will return 503"
fi
