"""Prompt text and payload construction for the LLM prose layer.

Two rules shape everything here:

1. The model never computes a number. It receives pre-formatted strings (``"$12.4M"``)
   alongside the raw values and is told to reuse them verbatim or say "not disclosed".
   Anything it emits still passes through `provenance.py` afterwards -- the prompt is
   the polite request, the gate is the enforcement.
2. The model never gets to decide what is important. Ranking, tiering, and the $5M gate
   are deterministic and already done by the time this runs. The model writes *language*
   about an ordering it cannot change.
"""

from __future__ import annotations

import json
from typing import Any

from whale_agent.models.event import NormalizedEvent
from whale_agent.summarization.render import format_usd

SYSTEM_PROMPT = """\
You write a concise, skeptical market-awareness digest for one reader. Write it like a \
person who scanned the filings and is telling someone what actually happened: plain \
words, short sentences, concrete detail, no compliance-memo throat-clearing. You are \
not giving investment advice, and you never predict prices or recommend action, but say \
what happened directly and let the restraint show up in what you decline to claim, not \
in how you phrase what you do claim.

Hard rules, in order of importance:
1. Use ONLY the numbers present in the JSON you are given. Do not compute, sum, \
average, round, rescale, or invent any figure. If you want to state a magnitude, copy \
the `usd_display` string exactly as given.
2. If a value is null, write "not disclosed". Never estimate it.
3. Do not introduce facts that are not in the JSON: no prices, no market caps, no \
performance history, no news, no company descriptions.
4. Be skeptical by default. Insider buys are more informative than sells. Routine \
trades, compensation grants, option exercises, and scheduled 10b5-1 sales carry little \
signal and you should say so plainly.
5. Be terse. One sentence per event. No hype, no adjectives like "massive" or \
"stunning", no emoji.
6. Never use an em dash or en dash (— or –), in any sentence, for any reason. Use a \
period, a comma, or a colon instead. Never use "delve", "it's worth noting", "in the \
world of", "landscape", "tapestry", "navigating", "robust", "leverage" as a verb, \
"underscores", "highlights the importance", "in today's", "furthermore", "moreover", or \
a sentence that just restates its own heading.

Return STRICT JSON, no markdown fences, matching exactly this shape:

{
  "headline": "<two sentences summarizing the day, no numbers unless copied verbatim>",
  "items": [
    {"event_id": "<id from input>",
     "why_it_matters": "<one sentence>",
     "skeptic_note": "<one sentence, or empty string if nothing to caveat>"}
  ]
}
"""


_MAX_NAME_LEN = 120

# Characters that only ever appear in a filer or issuer name because someone put them
# there on purpose: markdown/prompt structure, fenced blocks, and the role tags a chat
# transcript uses. A legal entity name needs none of them.
_INJECTION_CHARS = str.maketrans({c: " " for c in "<>{}[]|`#*_\\\n\r\t"})


def scrub_untrusted_text(value: str | None) -> str:
    """Flatten a third-party-controlled string before it reaches the model's context.

    Filer and issuer names arrive from filings, vendor JSON, and scraped HTML. They are
    attacker-influenced in the strict sense: registering an entity is enough to choose
    one. The numeric provenance gate downstream catches invented *figures*, but it has
    nothing to say about a name that reads as an instruction, so the defence for that
    has to happen before the text is ever placed in the prompt.

    This is deliberately blunt -- strip structural characters, collapse whitespace,
    truncate -- because the goal is not to interpret the string, only to ensure it can
    only ever be read as a name. Anything lost to scrubbing was not a name.
    """
    if not value:
        return ""
    flattened = " ".join(value.translate(_INJECTION_CHARS).split())
    if len(flattened) > _MAX_NAME_LEN:
        flattened = flattened[:_MAX_NAME_LEN].rstrip() + "..."
    return flattened


def event_payload(event: NormalizedEvent) -> dict[str, Any]:
    """The only view of an event the model ever sees.

    Deliberately narrow: identifiers, categorical flags, and pre-formatted magnitude
    strings. Scores and internal multipliers are excluded -- they are not meaningful to
    a reader and would only invite the model to quote them as if they were data.

    The two free-text fields are the ones nobody here controls, so both go through
    `scrub_untrusted_text` on the way in. Every other field below is either generated by
    this codebase or constrained to an enum, and so has nothing to inject with.
    """
    return {
        "event_id": event.event_id,
        "filer_name": scrub_untrusted_text(event.filer_name),
        "filer_type": event.filer_type,
        "issuer_name": scrub_untrusted_text(event.issuer_name),
        "ticker": event.ticker,
        "jurisdiction": event.jurisdiction.value,
        "action": event.transaction_type.value,
        "usd_display": format_usd(event.effective_usd),
        "usd_is_estimate": event.usd_value_is_estimate,
        "price_source": event.price_source.value,
        "percent_of_company": event.percent_of_company,
        "transaction_date": event.transaction_date.isoformat(),
        "disclosure_date": event.disclosure_date.isoformat(),
        "is_first_time_filer": event.is_first_time_filer,
        "is_routine": event.is_routine,
        "cluster_size": event.cluster_size,
        "tier": event.tier.value if event.tier else None,
    }


def build_user_prompt(
    events: list[NormalizedEvent], coverage_notes: list[str] | None = None
) -> str:
    """Serialize the ranked events (highest first) as the model's sole input."""
    payload: dict[str, Any] = {
        "events_ranked_most_to_least_notable": [event_payload(e) for e in events],
    }
    if coverage_notes:
        payload["coverage_notes"] = coverage_notes
    return "Write the digest prose for the following already-ranked events.\n\n" + json.dumps(
        payload, indent=2, ensure_ascii=False
    )
